/**
 * ============================================================
 * Booking Service
 * ============================================================
 *
 * Handles all booking lifecycle operations: create, read,
 * cancel, and reschedule — backed by the Firestore "bookings"
 * collection.
 *
 * Firestore "bookings" collection schema
 * ----------------------------------------
 * Document ID = auto-generated by Firestore (addDoc)
 * {
 *   bookingId:       string    – same as the auto-generated doc ID
 *   userId:          string    – UID of the user who booked
 *   salonId:         string    – ID of the booked salon
 *   salonName:       string    – display name of the salon
 *   service:         string    – name of the service booked
 *   appointmentDate: string    – date in "YYYY-MM-DD" format
 *   appointmentTime: string    – time in "HH:MM" (24-hr) format
 *   status:          string    – "confirmed" | "cancelled"
 *   createdAt:       timestamp – server-generated timestamp
 * }
 *
 * Validation rules enforced
 * --------------------------
 *   • No empty fields.
 *   • appointmentDate must be today or in the future.
 *   • No duplicate booking for the same salon + date + time
 *     (prevents double-booking a slot).
 *
 * Exported functions
 * ------------------
 *   createBooking(bookingData)                        → DocumentReference
 *   getUserBookings(userId)                            → Array<Booking>
 *   getBookingById(bookingId)                          → Booking | null
 *   cancelBooking(bookingId)                           → void
 *   rescheduleBooking(bookingId, newDate, newTime)     → void
 * ============================================================
 */

import {
  collection,
  addDoc,
  getDocs,
  doc,
  getDoc,
  updateDoc,
  deleteDoc,
  query,
  where,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../firebase/firebaseConfig.js";

// Reference to the top-level "bookings" collection.
const bookingsCollection = collection(db, "bookings");

// ---------------------------------------------------------------
// Helper – date validation
// ---------------------------------------------------------------
/**
 * Returns true if the supplied date string (YYYY-MM-DD) is
 * today or in the future, based on the local system clock.
 *
 * @param {string} dateStr – Date in "YYYY-MM-DD" format.
 * @returns {boolean}
 */
function isDateTodayOrFuture(dateStr) {
  // Build a Date object from the string. We compare only the
  // calendar date (ignoring time) by resetting hours to midnight.
  const inputDate = new Date(dateStr + "T00:00:00");
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return inputDate >= today;
}

// ---------------------------------------------------------------
// Helper – duplicate check
// ---------------------------------------------------------------
/**
 * Queries Firestore for any existing *confirmed* booking at
 * the given salon, date, and time. Returns true if a conflict
 * exists.
 *
 * We use a compound Firestore query with three `where` clauses.
 * NOTE: Firestore may require a composite index for this query.
 * If you see an index error in the console, follow the link
 * Firebase provides to create the index automatically.
 *
 * @param {string} salonId         – Salon document ID.
 * @param {string} appointmentDate – "YYYY-MM-DD".
 * @param {string} appointmentTime – "HH:MM".
 * @returns {Promise<boolean>} true if a conflicting booking exists.
 */
async function isDuplicateBooking(salonId, appointmentDate, appointmentTime) {
  const q = query(
    bookingsCollection,
    where("salonId", "==", salonId),
    where("appointmentDate", "==", appointmentDate),
    where("appointmentTime", "==", appointmentTime),
    where("status", "==", "confirmed")
  );

  const snapshot = await getDocs(q);
  // If at least one document matches, the slot is already taken.
  return !snapshot.empty;
}

// ---------------------------------------------------------------
// createBooking
// ---------------------------------------------------------------
/**
 * Creates a new booking document in Firestore after validating
 * all inputs and checking for scheduling conflicts.
 *
 * @param {Object} bookingData
 * @param {string} bookingData.userId          – Auth UID.
 * @param {string} bookingData.salonId         – Salon doc ID.
 * @param {string} bookingData.salonName       – Salon display name.
 * @param {string} bookingData.service         – Service name.
 * @param {string} bookingData.appointmentDate – "YYYY-MM-DD".
 * @param {string} bookingData.appointmentTime – "HH:MM".
 * @returns {Promise<import("firebase/firestore").DocumentReference>}
 * @throws {Error} On validation failure or scheduling conflict.
 */
export async function createBooking({
  userId,
  salonId,
  salonName,
  service,
  appointmentDate,
  appointmentTime,
}) {
  // ---- Field-presence validation ----
  if (!userId || !userId.trim())
    throw new Error("User ID is required.");
  if (!salonId || !salonId.trim())
    throw new Error("Salon ID is required.");
  if (!salonName || !salonName.trim())
    throw new Error("Salon name is required.");
  if (!service || !service.trim())
    throw new Error("Service is required.");
  if (!appointmentDate || !appointmentDate.trim())
    throw new Error("Appointment date is required.");
  if (!appointmentTime || !appointmentTime.trim())
    throw new Error("Appointment time is required.");

  // ---- Past-date validation ----
  // Reject any date that has already passed.
  if (!isDateTodayOrFuture(appointmentDate)) {
    throw new Error(
      "Cannot book a past date. Please choose today or a future date."
    );
  }

  // ---- Duplicate-booking validation ----
  // Check that no confirmed booking already occupies this slot.
  const duplicate = await isDuplicateBooking(
    salonId.trim(),
    appointmentDate.trim(),
    appointmentTime.trim()
  );
  if (duplicate) {
    throw new Error(
      "This time slot is already booked at the selected salon. Please choose a different date or time."
    );
  }

  // ---- Write to Firestore ----
  // `addDoc` creates a new document with an auto-generated ID.
  const docRef = await addDoc(bookingsCollection, {
    userId: userId.trim(),
    salonId: salonId.trim(),
    salonName: salonName.trim(),
    service: service.trim(),
    appointmentDate: appointmentDate.trim(),
    appointmentTime: appointmentTime.trim(),
    status: "confirmed",
    createdAt: serverTimestamp(),
  });

  // Store the auto-generated ID back into the document as
  // `bookingId` for convenient lookup.
  await updateDoc(docRef, { bookingId: docRef.id });

  return docRef;
}

// ---------------------------------------------------------------
// getUserBookings
// ---------------------------------------------------------------
/**
 * Retrieves all bookings belonging to a specific user.
 *
 * Uses a Firestore `where` query to filter on the `userId` field.
 *
 * @param {string} userId – Auth UID of the user.
 * @returns {Promise<Array<Object>>} Array of booking objects.
 * @throws {Error} If userId is empty.
 */
export async function getUserBookings(userId) {
  if (!userId || !userId.trim()) {
    throw new Error("User ID is required to fetch bookings.");
  }

  // Build a query that filters bookings by the given userId.
  const q = query(
    bookingsCollection,
    where("userId", "==", userId.trim())
  );

  const snapshot = await getDocs(q);

  // Convert each Firestore document snapshot to a plain object.
  return snapshot.docs.map((docSnap) => ({
    id: docSnap.id,
    ...docSnap.data(),
  }));
}

// ---------------------------------------------------------------
// getBookingById
// ---------------------------------------------------------------
/**
 * Fetches a single booking document by its Firestore ID.
 *
 * @param {string} bookingId – Firestore document ID.
 * @returns {Promise<Object|null>} The booking, or null if not found.
 * @throws {Error} If bookingId is empty.
 */
export async function getBookingById(bookingId) {
  if (!bookingId || !bookingId.trim()) {
    throw new Error("Booking ID is required.");
  }

  const bookingRef = doc(db, "bookings", bookingId.trim());
  const bookingSnap = await getDoc(bookingRef);

  if (!bookingSnap.exists()) {
    return null;
  }

  return { id: bookingSnap.id, ...bookingSnap.data() };
}

// ---------------------------------------------------------------
// cancelBooking
// ---------------------------------------------------------------
/**
 * Marks a booking as "cancelled" by updating its `status` field.
 *
 * We use `updateDoc` instead of `deleteDoc` to preserve an
 * audit trail. If you prefer hard deletes, swap `updateDoc`
 * for `deleteDoc(bookingRef)`.
 *
 * @param {string} bookingId – Firestore document ID.
 * @returns {Promise<void>}
 * @throws {Error} If the booking doesn't exist or is already cancelled.
 */
export async function cancelBooking(bookingId) {
  if (!bookingId || !bookingId.trim()) {
    throw new Error("Booking ID is required.");
  }

  const bookingRef = doc(db, "bookings", bookingId.trim());
  const bookingSnap = await getDoc(bookingRef);

  // Ensure the booking actually exists before updating.
  if (!bookingSnap.exists()) {
    throw new Error("Booking not found.");
  }

  // Prevent cancelling an already-cancelled booking.
  if (bookingSnap.data().status === "cancelled") {
    throw new Error("This booking is already cancelled.");
  }

  // Update only the `status` field — all other fields stay intact.
  await updateDoc(bookingRef, { status: "cancelled" });
}

// ---------------------------------------------------------------
// rescheduleBooking
// ---------------------------------------------------------------
/**
 * Changes the date and/or time of an existing confirmed booking.
 *
 * Validates the new date/time the same way `createBooking` does:
 *   • Must not be in the past.
 *   • Must not conflict with another confirmed booking.
 *
 * @param {string} bookingId – Firestore document ID.
 * @param {string} newDate   – New date in "YYYY-MM-DD" format.
 * @param {string} newTime   – New time in "HH:MM" format.
 * @returns {Promise<void>}
 * @throws {Error} On validation failure, conflict, or missing booking.
 */
export async function rescheduleBooking(bookingId, newDate, newTime) {
  // ---- Validate inputs ----
  if (!bookingId || !bookingId.trim())
    throw new Error("Booking ID is required.");
  if (!newDate || !newDate.trim())
    throw new Error("New appointment date is required.");
  if (!newTime || !newTime.trim())
    throw new Error("New appointment time is required.");

  // ---- Past-date check ----
  if (!isDateTodayOrFuture(newDate)) {
    throw new Error(
      "Cannot reschedule to a past date. Please choose today or a future date."
    );
  }

  // ---- Fetch the existing booking ----
  const bookingRef = doc(db, "bookings", bookingId.trim());
  const bookingSnap = await getDoc(bookingRef);

  if (!bookingSnap.exists()) {
    throw new Error("Booking not found.");
  }

  const bookingData = bookingSnap.data();

  // Cannot reschedule a cancelled booking.
  if (bookingData.status === "cancelled") {
    throw new Error("Cannot reschedule a cancelled booking.");
  }

  // ---- Duplicate check for the new slot ----
  const duplicate = await isDuplicateBooking(
    bookingData.salonId,
    newDate.trim(),
    newTime.trim()
  );
  if (duplicate) {
    throw new Error(
      "The new time slot is already booked. Please choose a different date or time."
    );
  }

  // ---- Apply the update ----
  // Only the date and time fields are changed.
  await updateDoc(bookingRef, {
    appointmentDate: newDate.trim(),
    appointmentTime: newTime.trim(),
  });
}
