/**
 * ============================================================
 * Salon Service
 * ============================================================
 *
 * CRUD operations for the Firestore "salons" collection.
 *
 * Firestore "salons" collection schema
 * -------------------------------------
 * Document ID = auto-generated by Firestore (addDoc)
 * {
 *   salonId:   string   – same as the auto-generated doc ID
 *   name:      string   – salon display name
 *   location:  string   – address or area description
 *   rating:    number   – average star rating (0-5)
 *   services:  string[] – list of services offered
 * }
 *
 * Exported functions
 * ------------------
 *   addSalon(salonData)    → DocumentReference
 *   getAllSalons()          → Array<Salon>
 *   getSalonById(salonId)  → Salon | null
 * ============================================================
 */

import {
  collection,
  addDoc,
  getDocs,
  doc,
  getDoc,
  updateDoc,
} from "firebase/firestore";
import { db } from "../firebase/firebaseConfig.js";

// Reference to the top-level "salons" collection.
const salonsCollection = collection(db, "salons");

// ---------------------------------------------------------------
// addSalon
// ---------------------------------------------------------------
/**
 * Adds a new salon document to Firestore.
 *
 * Firestore's `addDoc` generates a unique document ID
 * automatically. After creation we update the document to store
 * that ID as the `salonId` field for easy querying later.
 *
 * @param {Object} salonData
 * @param {string} salonData.name      – Salon name.
 * @param {string} salonData.location  – Salon address / area.
 * @param {number} salonData.rating    – Star rating (0-5).
 * @param {string[]} salonData.services – Services offered.
 * @returns {Promise<import("firebase/firestore").DocumentReference>}
 * @throws {Error} If required fields are missing or invalid.
 */
export async function addSalon({ name, location, rating, services }) {
  // --- Validation ---
  if (!name || !name.trim()) {
    throw new Error("Salon name is required.");
  }
  if (!location || !location.trim()) {
    throw new Error("Salon location is required.");
  }
  if (rating === undefined || rating === null || typeof rating !== "number") {
    throw new Error("Rating must be a number.");
  }
  if (rating < 0 || rating > 5) {
    throw new Error("Rating must be between 0 and 5.");
  }
  if (!Array.isArray(services) || services.length === 0) {
    throw new Error("At least one service must be provided.");
  }

  // Step 1 – Create the document. Firestore assigns a unique ID.
  const docRef = await addDoc(salonsCollection, {
    name: name.trim(),
    location: location.trim(),
    rating,
    services,
  });

  // Step 2 – Write the auto-generated ID back into the document
  // as `salonId` so consumers don't need to track the doc ref.
  await updateDoc(docRef, { salonId: docRef.id });

  return docRef;
}

// ---------------------------------------------------------------
// getAllSalons
// ---------------------------------------------------------------
/**
 * Fetches every salon document from Firestore.
 *
 * `getDocs` retrieves a QuerySnapshot containing all documents
 * in the "salons" collection. We iterate and return plain objects.
 *
 * @returns {Promise<Array<Object>>} Array of salon objects.
 */
export async function getAllSalons() {
  // Fetch the entire collection snapshot.
  const snapshot = await getDocs(salonsCollection);

  // Map each document snapshot to a plain JS object.
  // `doc.data()` returns the document's field values.
  const salons = snapshot.docs.map((docSnap) => ({
    id: docSnap.id, // Firestore document ID
    ...docSnap.data(), // Spread all fields (name, location, etc.)
  }));

  return salons;
}

// ---------------------------------------------------------------
// getSalonById
// ---------------------------------------------------------------
/**
 * Fetches a single salon document by its Firestore document ID.
 *
 * `doc(db, "salons", id)` creates a DocumentReference, and
 * `getDoc` retrieves that specific document.
 *
 * @param {string} salonId – Firestore document ID for the salon.
 * @returns {Promise<Object|null>} The salon object, or null if
 *   no document exists with that ID.
 * @throws {Error} If salonId is empty.
 */
export async function getSalonById(salonId) {
  if (!salonId || !salonId.trim()) {
    throw new Error("Salon ID is required.");
  }

  // Build a reference to the specific document.
  const salonRef = doc(db, "salons", salonId.trim());

  // Fetch the document snapshot.
  const salonSnap = await getDoc(salonRef);

  // `exists()` returns false if the document was not found.
  if (!salonSnap.exists()) {
    return null;
  }

  return { id: salonSnap.id, ...salonSnap.data() };
}
