/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SalonsRouteImport } from './routes/salons'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonsIdRouteImport } from './routes/salons.$id'
import { Route as BookSalonIdRouteImport } from './routes/book.$salonId'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsRoute = SalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIdRoute = SalonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalonsRoute,
} as any)
const BookSalonIdRoute = BookSalonIdRouteImport.update({
  id: '/book/$salonId',
  path: '/book/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/quiz': typeof QuizRoute
  '/routine': typeof RoutineRoute
  '/salons': typeof SalonsRouteWithChildren
  '/trends': typeof TrendsRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/quiz': typeof QuizRoute
  '/routine': typeof RoutineRoute
  '/salons': typeof SalonsRouteWithChildren
  '/trends': typeof TrendsRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/quiz': typeof QuizRoute
  '/routine': typeof RoutineRoute
  '/salons': typeof SalonsRouteWithChildren
  '/trends': typeof TrendsRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$id': typeof SalonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/inspiration'
    | '/quiz'
    | '/routine'
    | '/salons'
    | '/trends'
    | '/book/$salonId'
    | '/salons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/inspiration'
    | '/quiz'
    | '/routine'
    | '/salons'
    | '/trends'
    | '/book/$salonId'
    | '/salons/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/inspiration'
    | '/quiz'
    | '/routine'
    | '/salons'
    | '/trends'
    | '/book/$salonId'
    | '/salons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  InspirationRoute: typeof InspirationRoute
  QuizRoute: typeof QuizRoute
  RoutineRoute: typeof RoutineRoute
  SalonsRoute: typeof SalonsRouteWithChildren
  TrendsRoute: typeof TrendsRoute
  BookSalonIdRoute: typeof BookSalonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons': {
      id: '/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof SalonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$id': {
      id: '/salons/$id'
      path: '/$id'
      fullPath: '/salons/$id'
      preLoaderRoute: typeof SalonsIdRouteImport
      parentRoute: typeof SalonsRoute
    }
    '/book/$salonId': {
      id: '/book/$salonId'
      path: '/book/$salonId'
      fullPath: '/book/$salonId'
      preLoaderRoute: typeof BookSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SalonsRouteChildren {
  SalonsIdRoute: typeof SalonsIdRoute
}

const SalonsRouteChildren: SalonsRouteChildren = {
  SalonsIdRoute: SalonsIdRoute,
}

const SalonsRouteWithChildren =
  SalonsRoute._addFileChildren(SalonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  InspirationRoute: InspirationRoute,
  QuizRoute: QuizRoute,
  RoutineRoute: RoutineRoute,
  SalonsRoute: SalonsRouteWithChildren,
  TrendsRoute: TrendsRoute,
  BookSalonIdRoute: BookSalonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
